POST http://localhost:4000/app/signup
Content-Type: application/json

{
    "FullName":"chamali",
    "userName":"Hirunika",
    "email":"hirunika2018@gmail.com",
    "password":"2807",
    "Date":"2022.02.07"
}

